version: '3.8'

services:
  db:
    image: postgres:15
    container_name: uniesquina-db
    restart: always
    environment:
      POSTGRES_USER: uniesquina
      POSTGRES_PASSWORD: uniesquina123
      POSTGRES_DB: uniesquina_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./uniesquina-frontend
      dockerfile: Dockerfile
    container_name: uniesquina-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./uniesquina-frontend:/app
      - /app/node_modules
    depends_on:
      - db


  backend:
    build:
      context: ./uniesquina-backend
      dockerfile: Dockerfile
    container_name: uniesquina-backend
    ports:
      - "8080:8080"
    volumes:
      - ./uniesquina-backend:/app
      - /app/target
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/uniesquina_db
      - SPRING_DATASOURCE_USERNAME=uniesquina
      - SPRING_DATASOURCE_PASSWORD=uniesquina123
    depends_on:
      - db

volumes:
  postgres_data:
