version: '3.8'

services:
  db:
    image: postgres:15
    container_name: uniesquina-db
    restart: always
    environment:
      POSTGRES_USER: uniesquina
      POSTGRES_PASSWORD: uniesquina123
      POSTGRES_DB: uniesquina_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./uniesquina-frontend
      dockerfile: Dockerfile
    container_name: uniesquina-frontend
    ports:
      - "4200:80"
    depends_on:
      - db

volumes:
  postgres_data:
